# -----------------------------------------------
# Jekyll Configuration
# -----------------------------------------------

markdown: rdiscount
permalink: pretty
pygments: false

# -----------------------------------------------
# Site-specific Settings
# -----------------------------------------------

author: John Doe
author_email: john@doe.com
title: Jekyll Zurb Prose Heroku Travis Quickstart
url: http://localhost:4444
